Minor bug fixes.

diff --git a/crop-geometry b/crop-geometry
--- a/crop-geometry
+++ b/crop-geometry
@@ -34,7 +34,7 @@ set -e -o pipefail
 shopt -s inherit_errexit
 
 die() {
-	echo >&2 "ERROR: $@"
+	echo >&2 "ERROR:" "$@"
 	exit 1
 }
 
