Stylistic changes.

diff --git a/crop-geometry b/crop-geometry
--- a/crop-geometry
+++ b/crop-geometry
@@ -46,7 +46,7 @@ Usage:
 	$(basename "$0") left% right% top% bottom% input-file-name
 where
 	"left", "right", "top", and "bottom" (in this order) are percentages
-	of the image to crop from the respective sides of the image. Range of
+	of the image to crop from the respective sides of the image. The range of
 	values is from 0 to 99.99%, with up to 2 digits after the decimal point.
 	Percent symbol '%' is optional.
 Example:
@@ -58,35 +58,33 @@ EOF
 # check parameters
 [ $# -eq 5 ] || usage
 
-input_file="$5"
-
 # input image dimensions
-read w h < <(identify -format "%w %h\n" "$input_file")
+read -r W H < <(identify -format "%w %h\n" "$5")
 
 # read crop values
 read_param() {
-	local -r param_re='^[0-9]{1,2}(\.[0-9]{,2})?%?$'	# values from 0 to 99.99%
+	local -r VALID='^[0-9]{1,2}(\.[0-9]{,2})?%?$'	# values from 0 to 99.99%
 
-	[[ "$2" =~ $param_re ]] || die "Invalid value for \"$1\": $2"
+	[[ "$2" =~ $VALID ]] || die "Invalid value for \"$1\": $2"
 
 	case "$1" in
 		# https://stackoverflow.com/questions/26861118/rounding-numbers-with-bc-in-bash
-		top | bottom)	bc <<< "scale = 2; x = 0.5 + ($h * $2) / 100; scale = 0; x / 1" ;;
-		left | right)	bc <<< "scale = 2; x = 0.5 + ($w * $2) / 100; scale = 0; x / 1" ;;
-		*) 				die "Unknown image side: \"$1\"" ;;
+		top | bottom)	bc <<< "scale = 2; x = 0.5 + ($H * $2) / 100; scale = 0; x / 1" ;;
+		left | right)	bc <<< "scale = 2; x = 0.5 + ($W * $2) / 100; scale = 0; x / 1" ;;
+		*) 				die "Unknown image side: \"$1\"" ;;	# this should never happen
 	esac
 }
 
-l=$(read_param "left" "$1")
-r=$(read_param "right" "$2")
-t=$(read_param "top" "$3")
-b=$(read_param "bottom" "$4")
+L=$(read_param "left" "$1")
+R=$(read_param "right" "$2")
+T=$(read_param "top" "$3")
+B=$(read_param "bottom" "$4")
 
 # check for empty image
-[ $((t + b)) -lt $h -a $((l + r)) -lt $w ] || exec echo "1x1-10-10"	# empty image with warning from `convert`
+[ $((T + B)) -lt $H -a $((L + R)) -lt $W ] || exec echo "1x1-10-10"	# empty image with warning from `convert`
 
 # finally, compose the string
-echo "$(($w - $l - $r))x$(($h - $t - $b))+$l+$t"
+echo "$((W - L - R))x$((H - T - B))+$L+$T"
 
 # Example command:
 #	convert input_file +repage -crop "$(crop-geometry 10 10 10 10 input-file)" +repage $output_file
