First working version.

diff --git a/ocr b/ocr
--- a/ocr
+++ b/ocr
@@ -3,9 +3,6 @@
 # version
 declare -r VERSION=0.0.1
 
-# number of processors
-NPROC=$(nproc) ; [ $? -ne 0 ] && exit 1 ; declare -r -i NPROC
-
 # helper functions
 function _check_program() {
 	# https://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
@@ -13,33 +10,24 @@ function _check_program() {
 }
 
 function _show_usage() {
-	cat << EOF >&2
-Usage: $0 [OPTION]... FILE
-Extract text from a scanned pdf or djvu document FILE.
-Options:
-  -f N     first page number (optional, default: 1)
-  -l N     last page number (optional, default: last page of the document)
-  -L LANG  document language (optional, default: 'eng')
-  -o FILE  output file name (optional, default: stdout)
-  -w DIR   working directory (optional, default: a temporary directory)
-  -h       display this help and exit
-  -v       output version information and exit
-EOF
+	cat <<-EOF >&2
+	Usage: $0 [OPTION]... FILE
+	Extracts text from a scanned pdf or djvu document FILE.
+	Options:
+	  -f N     first page number (optional, default: 1)
+	  -l N     last page number (optional, default: last page of the document)
+	  -L LANG  document language (optional, default: 'eng')
+	  -o FILE  output file name (optional, default: stdout)
+	  -w DIR   working directory (optional, default: a temporary directory)
+	  -h       display this help and exit
+	  -v       output version information and exit
+	EOF
 }
 
 function _ddjvu_exit() {
 	head -q -n 1 "$1" | sed 's/^ddjvu:[[:space:]]*\[[^]]*\]/ddjvu:/g' >&2
 	exit 1
 }
-
-# pdfimages
-_check_program pdfimages
-
-if [[ -z $(pdfimages --help 2>&1 | grep -E '^\s+\-tiff\s+') ]]
-then
-	echo "ERROR: Current version of \"pdfimages\" does not support .tiff output format" >&2
-	exit 1
-fi
 
 # tesseract
 _check_program tesseract
@@ -77,9 +65,10 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
 # input file
 case $# in
+	1)	declare -r INPUT_FILE=$1
+		[[ -f "$INPUT_FILE" ]] || { echo "ERROR: File not found: $INPUT_FILE" >&2 ; exit 1 ; } ;;
+
 	0)	printf "ERROR: Input file is not specified\n\n" >&2 ; _show_usage ; exit 1 ;;
-	1)	declare -r INPUT_FILE=$1 ;;
-#	1)	declare -r INPUT_FILE=$1 ; [[ -f "$INPUT_FILE" ]] || { echo "File not found: $INPUT_FILE" >&2 ; exit 1 ; } ;;
 	*)	echo "ERROR: Cannot process more than one input file: $@" >&2 ; exit 1 ;;
 esac
 
@@ -109,6 +98,47 @@ declare -r WORK_DIR
 #defaults
 declare -r OCR_LANG=${OCR_LANG:-eng}
 
+# extract images
+case "${INPUT_FILE##*.}" in
+	PDF|pdf)	# pdfimages
+		_check_program pdfimages
+
+		if [[ -z $(pdfimages --help 2>&1 | grep -E '^\s+\-tiff\s+') ]]
+		then
+			echo "ERROR: Current version of \"pdfimages\" does not support .tiff output format" >&2
+			exit 1
+		fi
+
+		pdfimages -tiff -f ${FIRST_PAGE:-1} -l ${LAST_PAGE:-5000} "$INPUT_FILE" "$WORK_DIR/img" || exit 1 ;;
+
+	djvu)	# ddjvu
+		_check_program ddjvu
+		ddjvu -format=tiff -mode=black -eachpage -page=${FIRST_PAGE:-1}-${LAST_PAGE:-5000} "$INPUT_FILE" "$WORK_DIR/img-%05d.tif" 2>"$WORK_DIR/ddjvu-error" \
+		|| _ddjvu_exit "$WORK_DIR/ddjvu-error" ;;
+
+	*)	# error
+		echo "ERROR: Unsupported file type: $INPUT_FILE" >&2 ; exit 1 ;;
+esac
+
+if [[ -z $(find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif) ]]	# for some reason 'ls' finds nothing at this point
+then
+	echo "ERROR: No images extracted, something must have gone wrong" >&2
+	exit 1
+fi
+
+# number of processors
+NPROC=$(nproc) ; [ $? -ne 0 ] && exit 1 ; declare -r -i NPROC
+
+# OCR
+find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif -print0 | xargs -0 -n 1 -P $NPROC -I % \
+	sh -c "tesseract \"%\" \"%\" -l \"$OCR_LANG\" 2>\"%.err\" || exit 255"
+
+if [[ $? -ne 0 ]]
+then
+	find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif.err -exec grep -i -E '^ERROR:?\s+' "{}" \; >&2
+	exit 1
+fi
+
 # output redirection
 if [[ -n "$OUT_FILE" ]]	# https://stackoverflow.com/a/20564208
 then
@@ -116,15 +146,12 @@ then
 	exec 1>"$OUT_FILE" || exit 1
 fi
 
-# extract images
-case "${INPUT_FILE##*.}" in
-	pdf)	pdfimages -tiff -f ${FIRST_PAGE:-1} -l ${LAST_PAGE:-5000} "$INPUT_FILE" "$WORK_DIR/img" || exit 1 ;;
-	djvu)	ddjvu -format=tiff -mode=black -eachpage -page=${FIRST_PAGE:-1}-${LAST_PAGE:-5000} "$INPUT_FILE" "$WORK_DIR/img-%05d.tif" 2>"$WORK_DIR/ddjvu-error" || _ddjvu_exit "$WORK_DIR/ddjvu-error" ;;
-	*)		echo "ERROR: Unsupported file type: $INPUT_FILE" >&2 ; exit 1 ;;
-esac
-
+# output
+find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif.txt -print0 | sort -z | xargs -0 -n 1 cat
 
 # test
+echo
+echo "---------------------------------------------"
 echo "Language:     $OCR_LANG"
 echo "First page:   $FIRST_PAGE"
 echo "Last page:    $LAST_PAGE"
