Document renderer.

diff --git a/render-document b/render-document
--- a/render-document
+++ b/render-document
@@ -33,20 +33,20 @@
 # version
 declare -r VERSION=0.5.0
 
-# helper functions
-function _check_program() {
-	# https://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
-	command -p -v "$@" >/dev/null 2>&1 || { echo "ERROR: Program \"$@\" is not found." >&2 ; exit 1 ; }
-}
+# constants
+declare -r EXT=pgm
+declare -r PREF=page
+declare -r -i DPI=600
 
+# helper functions
 function _show_usage() {
 	cat <<-EOF >&2
 	Usage: $0 [OPTION]... FILE
-	Extracts images from a scanned pdf or djvu document FILE.
+	Renders .pdf or .djvu document FILE to grayscale images in .$EXT format.
 	Options:
 	  -f N     first page number (optional, default: 1)
 	  -l N     last page number (optional, default: last page of the document)
-	  -o DIR   working directory (mandatory)
+	  -o DIR   output directory (mandatory)
 	  -h       display this help and exit
 	  -v       output version information and exit
 	EOF
@@ -78,8 +78,9 @@ done
 
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
-declare -r FIRST_PAGE=${FIRST_PAGE:-1}
-declare -r LAST_PAGE=${LAST_PAGE:-5000}
+# pages
+declare -r -i FIRST_PAGE=${FIRST_PAGE:-1}
+declare -r -i LAST_PAGE=${LAST_PAGE:-5000}
 
 # input file
 case $# in
@@ -107,38 +108,31 @@ elif [[ ! -d "$WORK_DIR" ]]	# create if does not exists
 then
 	mkdir "$WORK_DIR" || exit 1
 else	# clear if not empty
-	find "$WORK_DIR" -maxdepth 1 -type f \( -name \*.tif -o -name ddjvu-error \) -delete
+	find "$WORK_DIR" -maxdepth 1 -type f \( -name \*.$EXT -o -name ddjvu-error \) -delete
 fi
 
-# extract images
+# render
 case "${INPUT_FILE##*.}" in
-	PDF|pdf)	# pdfimages
-		_check_program pdfimages
-
-		if [[ -z $(pdfimages --help 2>&1 | grep -E '^\s+\-tiff\s+') ]]
-		then
-			echo "ERROR: Current version of \"pdfimages\" does not support .tiff output format" >&2
-			exit 1
-		fi
-
-		pdfimages -tiff -f $FIRST_PAGE -l $LAST_PAGE "$INPUT_FILE" "$WORK_DIR/img" || exit 1 ;;
+	PDF|pdf)	# pdftoppm
+		pdftoppm -gray -aa no -aaVector no -thinlinemode solid -r $DPI -f $FIRST_PAGE -l $LAST_PAGE "$INPUT_FILE" "$WORK_DIR/$PREF" || exit 1
+		;;
 
 	djvu)	# ddjvu
-		_check_program ddjvu
-
-		ddjvu -format=tiff -mode=black -eachpage -page=$FIRST_PAGE-$LAST_PAGE "$INPUT_FILE" "$WORK_DIR/img-%05d.tif" 2>"$WORK_DIR/ddjvu-error" \
+		ddjvu -format=$EXT -mode=black -scale=$DPI -eachpage -page=$FIRST_PAGE-$LAST_PAGE "$INPUT_FILE" "$WORK_DIR/$PREF-%04d.$EXT" 2>"$WORK_DIR/ddjvu-error" \
 		|| _ddjvu_exit "$WORK_DIR/ddjvu-error"
 
-		rm "$WORK_DIR/ddjvu-error" ;;
+		rm "$WORK_DIR/ddjvu-error"
+		;;
 
 	*)	# error
-		echo "ERROR: Unsupported file type: $INPUT_FILE" >&2 ; exit 1 ;;
+		echo "ERROR: Unsupported file type: $INPUT_FILE" >&2 ; exit 1
+		;;
 esac
 
-# check if anything has been extracted
-if [[ -z $(find "$WORK_DIR" -maxdepth 1 -type f -name \*.tif) ]]
+# check if anything has been produced
+if [[ -z $(find "$WORK_DIR" -maxdepth 1 -type f -name \*.$EXT) ]]
 then
-	echo "ERROR: No images extracted, something must have gone wrong" >&2
+	echo "ERROR: No pages rendered, something must have gone wrong" >&2
 	exit 1
 fi
 
